COLORS = [
    'DarkSeaGreen3', 'firebrick4', 'SlateBlue4', 
    'PaleVioletRed3', 'lavender blush', 'dark goldenrod', 'dark green',
    'yellow3', 'gray11', 'coral1', 'gray3', 'PaleVioletRed2',
    'dark violet', 'thistle3', 'gray60', 'coral4', 'DodgerBlue3',
    'gray28', 'gray', 'orchid3', 'brown2', 'DarkOliveGreen1',
    'DarkOrchid4', 'gray27', 'alice blue', 'gray5', 
    'LightGoldenrod1', 'gray36', 'gray7', 'tomato2', 
    'DarkGoldenrod1', 'gray84', 'OliveDrab1', 'PaleTurquoise4', 
    'PaleVioletRed4', 'goldenrod2', 'RoyalBlue4', 'lavender',
    'RoyalBlue1', 'IndianRed1', 'plum1', 'cyan4', 'lime green',
    'burlywood2', 'plum4', 'DarkGoldenrod2', 'gray15', 'gray34',
    'deep sky blue', 'red4', 'DarkOliveGreen4', 'SteelBlue3',
    'orange3', 'LightCyan2', 'goldenrod4', 'cadet blue',
    'powder blue', 'sienna2', 'firebrick2', 'gray43',
    'azure4', 'OrangeRed3', 'LightSteelBlue2', 'SpringGreen3',
    'gray75', 'burlywood1', 'salmon2', 'dark salmon',
    'gray29', 'gray78', 'CadetBlue1', 'SlateGray3', 'tan2',
    'gray95', 'VioletRed3', 'gray62', 'gold2', 'LightBlue3',
    'khaki', 'khaki3', 'gray91', 'gray87', 'light salmon',
    'light grey', 'gray77', 'thistle', 'plum2', 'SkyBlue2',
    'DeepSkyBlue3', 'SkyBlue1', 'misty rose', 'LightGoldenrod2',
    'pale violet red', 'cyan3', 'aquamarine4', 'MediumPurple1',
    'gray99', 'honeydew4', 'medium violet red', 'gray93', 'goldenrod1',
    'khaki4', 'DarkOrchid1', 'pink', 'burlywood3', 'blue violet',
    'medium sea green', 'SteelBlue4', 'turquoise3', 'burlywood4',
    'gray30', 'SteelBlue1', 'goldenrod3', 'gray50', 'DarkOrange2',
    'thistle4', 'tomato', 'gray6', 'DeepPink2', 'HotPink1',
    'light blue', 'medium purple', 'SlateBlue1', 'DodgerBlue4',
    'firebrick1', 'chartreuse3', 'HotPink3', 'light cyan', 'gray85',
    'MediumPurple2', 'gray71', 'tan1', 'RosyBrown1', 'medium spring green',
    'dark slate gray', 'LightSteelBlue4', 'salmon', 'cornsilk2',
    'IndianRed2', 'gray46', 'red', 'LightSkyBlue4', 'wheat3',
    'gray89', 'light sea green', 'gray63', 'OrangeRed2', 'LightSalmon2',
    'DarkSeaGreen1', 'DodgerBlue2', 'gray45', 'VioletRed2', 'gray88',
    'dark orchid', 'blue2', 'sienna1', 'maroon4', 'forest green',
    'dark orange', 'dodger blue', 'orange2', 'SeaGreen1',
    'PaleTurquoise3', 'magenta3', 'DeepPink4', 'salmon1', 'gray14',
    'pink2', 'SlateGray1', 'sea green', 'light pink',
    'DarkSlateGray2', 'PaleVioletRed1', 'gray33', 'LemonChiffon3',
    'DeepPink3', 'MistyRose2', 'gray32', 'LemonChiffon4',
    'turquoise', 'purple2', 'light slate blue', 
    'light goldenrod yellow', 'LightBlue1', 'chocolate1',
    'midnight blue', 'lemon chiffon', 'tomato4', 'olive drab',
    'gray31', 'SlateGray4', 'red2', 'gray17', 'PaleTurquoise1',
    'gray19', 'DarkOrchid2', 'PaleTurquoise2', 'gray48',
    'brown3', 'SlateBlue2', 'gray38', 'thistle2', 'gray73',
    'cornsilk4', 'gray83', 'IndianRed4', 'CadetBlue4',
    'LightGoldenrod4', 'VioletRed4', 'plum3', 'LavenderBlush2',
    'gray70', 'SpringGreen2', 'spring green', 'HotPink4',
    'SteelBlue2', 'gray94', 'maroon3', 'cyan', 'SkyBlue4',
    'green2', 'khaki1', 'dark sea green', 'gray72',
    'DarkGoldenrod3', 'dark olive green', 'gray22',
    'orange4', 'LightPink4', 'brown4', 'violet red',
    'gray65', 'thistle1', 'yellow4', 'light goldenrod',
    'turquoise4', 'OrangeRed4', 'aquamarine2', 'turquoise1',
    'pink1', 'gray18', 'OliveDrab2', 'gray35', 'pale green',
    'gray24', 'cornsilk3', 'ivory3', 'gray74', 'SeaGreen3',
    'tomato3', 'azure2', 'navy', 'orchid2', 'tan4',
    'yellow2', 'SlateBlue3', 'wheat1', 'CadetBlue3',
    'light yellow', 'mint cream', 'LightYellow3',
    'LightSkyBlue1', 'dim gray', 'ivory2', 'light slate gray',
    'saddle brown', 'sandy brown', 'firebrick3', 'PaleGreen3',
    'maroon', 'gray56', 'DarkGoldenrod4', 'dark khaki',
    'LightSkyBlue2', 'gray81', 'LightPink2', 'green3',
    'DarkSeaGreen2', 'gray9', 'light steel blue', 'gray4', 'gray10',
    'IndianRed3', 'indian red', 'sienna3', 'SpringGreen4',
    'MediumOrchid4', 'sienna4', 'DarkSlateGray3', 'gray13',
    'SkyBlue3', 'DeepSkyBlue2', 'RoyalBlue3', 'gray82',
    'peach puff', 'salmon3', 'LightCyan4', 'LightSkyBlue3',
    'green4', 'RoyalBlue2', 'chartreuse2', 'yellow green',
    'coral', 'gray54', 'HotPink2', 'coral3', 'orange red',
    'purple3', 'honeydew3', 'DarkOrange3', 'gray37', 'DarkOrchid3',
    'gray12', 'slate gray', 'gray79', 'light coral', 'LightPink3',
    'light sky blue', 'SeaGreen2', 'LightSalmon3', 'gray23',
    'gray53', 'RosyBrown2', 'gray25', 'gray69', 'orchid1',
    'gray68', 'DarkOliveGreen3', 'DarkSeaGreen4', 'gray98',
    'gray86', 'LightPink1', 'gray1', 'blue', 'turquoise2',
    'gray61', 'LemonChiffon2', 'aquamarine', 'brown1',
    'DarkSlateGray4', 'orchid4', 'MistyRose3', 'gold3',
    'gray67', 'lawn green', 'gray58', 'pink4', 'CadetBlue2',
    'chocolate2', 'gray47', 'cyan2', 'purple', 'LightSalmon4',
    'steel blue', 'LavenderBlush4', 'rosy brown', 'wheat2',
    'LavenderBlush3', 'yellow', 'azure', 'gray80', 'goldenrod',
    'PaleGreen2', 'LightCyan3', 'blue4', 'DarkOrange4',
    'DarkSlateGray1', 'medium blue', 'maroon2', 'maroon1',
    'pale goldenrod', 'coral2', 'red3', 'gold', 'gray90',
    'gray26', 'LightGoldenrod3', 'gray39', 'chocolate3',
    'gray76', 'deep pink', 'gray44', 'medium orchid', 'khaki2',
    'gray59', 'magenta2', 'orange', 'LightSteelBlue1',
    'DarkOliveGreen2', 'VioletRed1', 'gold4', 'LightBlue2',
    'RosyBrown4', 'gray40', 'MediumPurple4', 'dark slate blue',
    'medium turquoise', 'ivory4', 'LightYellow2', 'LightYellow4',
    'gray2', 'royal blue', 'gray20', 'gray49', 'LightSteelBlue3',
    'RosyBrown3', 'MediumPurple3', 'chartreuse4', 'azure3',
    'PaleGreen4', 'MediumOrchid1', 'salmon4', 'slate blue',
    'gray8', 'purple4', 'green yellow', 'wheat4', 'gray64', 'purple1',
    'PaleGreen1', 'magenta4', 'gray42', 'sky blue', 'DeepSkyBlue4',
    'LightBlue4', 'DarkOrange1', 'MistyRose4', 'gray21',
    'pale turquoise', 'OliveDrab4', 'SlateGray2', 'cornflower blue',
    'MediumOrchid2', 'honeydew2', 'gray66', 'gray55',
    'medium slate blue', 'pink3', 'gray97', 'medium aquamarine',
    'gray51', 'MediumOrchid3', 'gray16', 'dark turquoise',
    'gray92', 'hot pink'
]
